### ISSUE TITLE
🐛 Bug: 

### ISSUE THREAD

**Issue by seveibar** [JoshuaKGoldberg/prune-github-notifications#168]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/prune-github-notifications/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

All github notifications with "subscribed" next to them to be cleared when I `prune-github-notifications --auth $(gh auth token) --watch 10`

### Actual

I still have notifications at https://github.com/notifications with "subscribed"

![notifications on github](https://github.com/JoshuaKGoldberg/prune-github-notifications/assets/1910070/ee62b50f-fdd1-423f-8593-2f631a98703b)

**Comment by seveibar** [comment]
Investigating the source code, it looks like this is because I was confused a bit:

```ts
// options.ts
import { PruneGitHubNotificationsOptions } from "./types.js";

export const defaultOptions = {
	// https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits
	// 1800 points per minute, or 30 points per second
	// 5 points per DELETE request
	// 30 points per second / 5 points per DELETE request = 6 simultaneous requests
	bandwidth: 6,

	filters: {
		reason: new Set(["subscribed"]),
		title: /^chore\(deps\): update .+ to/,
	},
} satisfies PruneGitHubNotificationsOptions;
```

Basically all the "chore" stuff is filtered out but not "Update Dependency" which I guess people might want by default. I'll try to configure the tool for my use case!

**Comment by JoshuaKGoldberg** [comment]
@seveibar ooh or maybe those titles should be included by default?

(on mobile, can talk more later)

**Comment by seveibar** [comment]
I got a configuration I liked with this!

```bash
prune-github-notifications --auth $(gh auth token) --reason subscribed --title ".+(U|u)pdate dependency.+" --watch 10
```

A couple ideas (happy to try to contrib as well- I really enjoyed reading the code- didn't know about knip!):
* README examples for common use cases
* Multiple reason/title support via CLI (or an example that shows it's possible, I _think_ it's not currently supported?)
* IMO including "update dependency" in the default would be reasonable- this is tough because I'm not sure how many people struggle with different types of notifications hehe- maybe update dependency is sometimes important? For me it's always been noise

**Comment by JoshuaKGoldberg** [comment]
@seveibar I like all of this! Since you're a collaborator on the repo now 😄 I'll defer to your judgement in filing issues.
